tgapi:
  address: "https://api.telegram.org/"
  token: "1607353956:AAGbM0Sp4d56fXK6zbBm9o252PRO9ON-gx4"

user_cache:
  database: "db.sqlite"

user_factory:
  dialog_timeout: 10m

poller:
  period: 5s

timer:
  period: 5s