version: "3.4"
services:
  bot:
    build:
      context: .
      target: bot
    environment:
      - TGBOT_TG_TOKEN
      - TGBOT_TG_ADDRESS
      - TGBOT_DB_DRIVER
      - TGBOT_DB_PATH
  mock:
    build:
      context: .
      target: mock
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
