tgapi:
  # TODO - move address to env
  address: "http://localhost:1234/"

user_cache:
  # TODO - move path to env
  driver: pg
  path: "pg:5432"

user_factory:
  dialog_timeout: 10m

poller:
  period: 5s

timer:
  period: 5s
